//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaasBordro.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBBORDROEntities : DbContext
    {
        public WEBBORDROEntities()
            : base("name=WEBBORDROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_BORDRO> TBL_BORDRO { get; set; }
        public virtual DbSet<TBL_DONEMLER> TBL_DONEMLER { get; set; }
        public virtual DbSet<TBL_MUDURLUK> TBL_MUDURLUK { get; set; }
        public virtual DbSet<TBL_PERSONEL> TBL_PERSONEL { get; set; }
    }
}
