//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaasBordro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONEL
    {
        public int IND { get; set; }
        public Nullable<int> PIND { get; set; }
        public Nullable<int> MIND { get; set; }
        public string TC_NO { get; set; }
        public string AD_SOYAD { get; set; }
        public string ISE_GIRIS_TARIHI { get; set; }
        public string SGK { get; set; }
        public string SIFRE { get; set; }
        public string KAYIT_TARIHI { get; set; }
        public string KAYDEDEN { get; set; }
    }
}
