//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaasBordro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DONEMLER
    {
        public int IND { get; set; }
        public Nullable<int> DIND { get; set; }
        public string DONEM { get; set; }
        public string KAYIT_TARIHI { get; set; }
        public string KAYDEDEN { get; set; }
    }
}
