//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaasBordro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BORDRO
    {
        public int IND { get; set; }
        public Nullable<int> PIND { get; set; }
        public Nullable<int> DIND { get; set; }
        public Nullable<int> MIND { get; set; }
        public Nullable<int> GUN { get; set; }
        public Nullable<decimal> NORMAL_KAZANC { get; set; }
        public Nullable<decimal> DIGER_KAZANC { get; set; }
        public Nullable<decimal> TOPLAM_KAZANC { get; set; }
        public Nullable<decimal> SSK_MATRAHI { get; set; }
        public Nullable<decimal> SSK_PRIMI { get; set; }
        public Nullable<decimal> ISSIZLIK_PRIMI { get; set; }
        public Nullable<decimal> GVM_AYLIK { get; set; }
        public Nullable<decimal> GVM_TOPLAM { get; set; }
        public Nullable<decimal> GELIR_VERGISI { get; set; }
        public Nullable<decimal> AGI { get; set; }
        public Nullable<decimal> KALAN_GELIR_VERGISI { get; set; }
        public Nullable<decimal> DAMGA_VERGISI { get; set; }
        public Nullable<decimal> OZEL_KESINTI { get; set; }
        public Nullable<decimal> AGI_HARIC_UCRET { get; set; }
        public Nullable<decimal> NET_ISTIHKAK { get; set; }
        public Nullable<decimal> NORMAL_UCRET { get; set; }
        public Nullable<decimal> GUN_UCRET { get; set; }
        public Nullable<decimal> FAZLA_MESAI_UCRET { get; set; }
        public string FAZLA_MESAI_SAAT { get; set; }
        public Nullable<decimal> TATIL_MESAI_UCRET { get; set; }
        public string TATIL_MESAI_GUN { get; set; }
        public Nullable<decimal> YEMEK_UCRETI { get; set; }
        public string YEMEK_GUNU { get; set; }
        public Nullable<decimal> COCUK_UCRETI { get; set; }
        public Nullable<decimal> PRIM { get; set; }
        public Nullable<decimal> YAKACAK_UCRETI { get; set; }
        public Nullable<decimal> HAFTASONU_MESAI_UCRETI { get; set; }
        public string HAFTASONU_MESAI_GUNU { get; set; }
        public Nullable<decimal> SENDIKA_KESINTISI { get; set; }
        public Nullable<decimal> AILE { get; set; }
        public Nullable<decimal> OTO_KAT_BE { get; set; }
        public Nullable<decimal> AVANS { get; set; }
        public Nullable<decimal> ICRA_KESINTISI { get; set; }
        public Nullable<decimal> RAPOR_UCRETI { get; set; }
        public string RAPOR_GUN { get; set; }
        public Nullable<decimal> NAFAGA_UCRETI { get; set; }
        public Nullable<System.DateTime> KAYIT_TARIHI { get; set; }
        public string KAYDEDEN { get; set; }
    }
}
